import { chromium } from 'playwright'; import fs from 'fs';
const html=fs.readFileSync('work/TOKYO_TEARDOWN_iPhone17_Enhanced.html','utf8'); const three=fs.readFileSync('work/lib/three.r128.min.js','utf8');
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const page=await ctx.newPage(); const errs=[];
page.on('pageerror',e=>errs.push(e.message)); page.on('console',m=>{ if(m.type()==='error') errs.push(m.text()); });
await page.addInitScript(()=>{ window.TT_DEBUG=true; window.TT_QUALITY='low'; });
await page.route('**/*',async route=>{ const u=route.request().url();
  if(u.includes('three')&&u.endsWith('.js')) return route.fulfill({status:200,contentType:'application/javascript',body:three});
  if(u.startsWith('http://local.test/')) return route.fulfill({status:200,contentType:'text/html',body:html}); return route.abort(); });
await page.goto('http://local.test/index.html');
await page.waitForFunction(()=>window.__tt&&!window.__tt.booting(),null,{timeout:150000}).catch(()=>{});
await page.evaluate(()=>{ const T=window.__tt; T.genCity(0); T.spawnOverview(); for(let i=0;i<300&&T.booting();i++) T.step(1/60); });
await page.waitForFunction(()=>!window.__tt.booting(),null,{timeout:120000});
await page.waitForTimeout(1500);
await page.click('#qbar .q.list'); await page.waitForTimeout(600);
await page.screenshot({path:'work/test/shot_sheet.png',timeout:120000});
const sheetOpen=await page.evaluate(()=>document.getElementById('wsheet').classList.contains('on'));
await page.click('#wgrid .w[data-w="nuke"]'); await page.waitForTimeout(300);
const sel=await page.evaluate(()=>({sheet:document.getElementById('wsheet').classList.contains('on'), first:document.querySelector('#qbar .q').dataset.w, n:document.querySelectorAll('#qbar .q').length}));
await page.click('#bPause'); await page.waitForTimeout(600);
const paused=await page.evaluate(()=>({menu:document.getElementById('pmenu').classList.contains('on'), paused:window.__tt.isPaused(), canShoot:window.__tt.canShoot()}));
await page.screenshot({path:'work/test/shot_menu.png',timeout:120000});
await page.click('#pmResume'); await page.waitForTimeout(300);
const resumed=await page.evaluate(()=>({menu:document.getElementById('pmenu').classList.contains('on'), paused:window.__tt.isPaused()}));
console.log(JSON.stringify({sheetOpen,sel,paused,resumed,errs:errs.slice(0,5)}));
await browser.close();
