// PC build screenshots at 1920x1080, 最高画質. usage: node work/test/shots_pc.mjs <html>
import { chromium } from 'playwright';
import fs from 'fs';
const file=process.argv[2]; const html=fs.readFileSync(file,'utf8');
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const page=await ctx.newPage(); const logs=[];
page.on('console',m=>{ if(m.type()==='error') logs.push(m.text().slice(0,200)); }); page.on('pageerror',e=>logs.push('[pageerror] '+e.message));
await page.addInitScript(()=>{ window.TT_DEBUG=true; window.TT_NOLOCK=true; window.TT_QUALITY='low'; window.__wb=()=>{ const T=window.__tt; for(let i=0;i<400&&T.booting&&T.booting();i++) T.step(1/60); }; });
await page.route('**/*',async route=>{ const u=route.request().url(); if(u.startsWith('http://local.test/')) return route.fulfill({status:200,contentType:'text/html',body:html}); return route.abort(); });
await page.goto('http://local.test/index.html');
await page.waitForFunction(()=>window.__tt && getComputedStyle(document.getElementById('boot')).display==='none',null,{timeout:200000});
fs.mkdirSync('work/test/pc_shots',{recursive:true});
const ev=(fn)=>page.evaluate(fn);
const AIMB=`(function(){ const T=window.__tt; T.cam.pos.set(0,70,260); T.cam.yaw=0; for(let p=-0.35;p<=0.15;p+=0.025){ T.cam.pitch=p; T.updCam(0.016); const h=T.aimRay(); if(!h.miss&&!h.ground&&h.d<420) return h.d; } })()`;
const shot=async(name,fn,wait)=>{ await ev(fn); await ev(()=>{ window.__tt.pc.resetFx(); }); await page.waitForTimeout(wait||2500); await page.screenshot({path:`work/test/pc_shots/${name}.png`,timeout:200000,animations:'disabled'}); console.log('shot',name); };
await ev(()=>{ const T=window.__tt; T.setQuality('ultra'); T.genCity(0,7); __wb(); T.spawnOverview(); T.selW('missile'); });
await shot('01_title',()=>{ window.__tt.pc.showTitle(); },3000);
await shot('02_kabukicho',()=>{ const T=window.__tt; T.pc.start(); T.spawnOverview(); },3000);
await shot('03_gun_hit',()=>{ const T=window.__tt; eval(`${''}`+`(function(){ const T=window.__tt; T.cam.pos.set(0,70,260); T.cam.yaw=0; for(let p=-0.35;p<=0.15;p+=0.025){ T.cam.pitch=p; T.updCam(0.016); const h=T.aimRay(); if(!h.miss&&!h.ground&&h.d<420) return h.d; } })()`); T.selW('gun'); T.gunTick(1/14*10); for(let i=0;i<12;i++) T.step(1/60); },1500);
await shot('04_carpet',()=>{ const T=window.__tt; T.selW('carpet'); T.setCd(0); T.fireWeapon(); for(let i=0;i<60*2.5;i++) T.step(1/60); },1500);
await shot('05_incend',()=>{ const T=window.__tt; T.genCity(0,7); __wb(); T.spawnOverview(); T.cam.pitch=-0.25; T.updCam(0.016); T.selW('incend'); T.setCd(0); T.fireWeapon(); for(let i=0;i<60*4;i++) T.step(1/60); },1500);
await shot('06_shibuya',()=>{ const T=window.__tt; T.genCity(1,7); __wb(); T.spawnOverview(); T.selW('missile'); },3000);
await shot('07_shinjuku_zoom',()=>{ const T=window.__tt; T.genCity(2,7); __wb(); T.spawnOverview(); T.pc.key('KeyV',true); T.pc.key('KeyV',false); for(let i=0;i<60;i++){ T.pc.readKeys(); T.updCam(1/30); } },3000);
await shot('08_weapon_panel',()=>{ const T=window.__tt; T.pc.key('KeyV',true); T.pc.key('KeyV',false); for(let i=0;i<60;i++){ T.pc.readKeys(); T.updCam(1/30); } T.pc.openPanel(); },1500);
await shot('09_menu',()=>{ const T=window.__tt; T.pc.closePanel(); T.pc.openMenu('menu'); },1500);
await shot('10_keys',()=>{ const T=window.__tt; T.pc.closeMenu(); T.pc.openKeys(); },1500);
await shot('11_topple',()=>{ const T=window.__tt; T.pc.key('Escape',true); T.pc.key('Escape',false); T.genCity(0,7); __wb(); eval(`(function(){ const T=window.__tt; T.cam.pos.set(0,70,260); T.cam.yaw=0; for(let p=-0.35;p<=0.15;p+=0.025){ T.cam.pitch=p; T.updCam(0.016); const h=T.aimRay(); if(!h.miss&&!h.ground&&h.d<420) return h.d; } })()`); T.selW('ball'); T.setCd(0); T.fireWeapon(); for(let i=0;i<60*2.2;i++) T.step(1/60); },1500);
console.log('errors',logs.length,logs.slice(0,3)); await browser.close();
